name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python for tests
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies and run tests
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-mock flake8
          
      - name: Lint with flake8
        run: flake8 --statistics

      - name: Unit testing with pytest
        env:
          API_BEARER_TOKEN: ${{ secrets.API_BEARER_TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: pytest --maxfail=0 --disable-warnings
